act_as_computer: |
  I want you to act like a computer program. I give you imput and you give me output in code

chats:
  analyze: |
    Analyze the conversation so far and return ONLY a JSON object with the following keys:

    `title`: an appropriate title in %{lang}
    `summary`: one paragraph summary in %{lang} that provides a brief overview of the conversation and highlights any significant points
    `tags`: array of lowercase tags in %{lang} that represent the main themes of our conversation
    `next`: array of questions in %{lang} you think the user could ask the assistant next

    You must ONLY return a valid, well-formatted JSON object
    that I can parse with no additional conversation or commentary.
    The values should all be %{lang}.
    Do NOT wrap the JSON code in markdown tags.
  consider: |
    Analyze the conversation and generate at least 3 observations like this:

    {
      "observations": [
        "most important observation or fact that should be definitely be remembered",
        "another observation or detail that can be gleaned from the conversation",
        "another observation or detail that can be gleaned from the conversation",
        ...
      ]
    }

    ONLY REPLY WITH VALID JSON that I can parse using Ruby's JSON.parse function!!!
  context_user: |
    Hi I'm %{user_name}. Very nice to be talking to you again today, %{bot_name}! I want you to address me by name, and
    ask me questions because it'll make me feel great about talking to you. FYI today is %{date} and we started this
    conversation at %{time}.
  context_top_memories: |
    These are the most important observations that you logged as memories during our
    previous conversations: %{m}. If anything sounds really important you might want to ask me about it.
    Finally, the remainder of this chat will be spoken in %{lang}. It's very important that you only speak to me in %{lang}.
  context_reply: |
    Good to be talking to you again, and thanks for reminding me of my memories! Yes, from here on out I will reply in %{lang}, no problem!

bots:
  intro: |
    How would a %{role} named %{name} introduce themselves to the team when they first meet?
    Reply in the voice of the %{role} without further commentary.
  start: |
    You are %{name}, %{role}.

    Your decisions must always be made independently without
    seeking user assistance. Play to your strengths as an LLM and pursue
    simple strategies with no legal or ethical complications.

    GOALS: %{goals}

dynamic_text: |
  How do you say "%{t}" in clean, well-written %{l} suitable for use as copy in a web application?
  Do not add any commentary. Only respond with the answer. If your response is just a single word
  or short phrase then do not use any punctuation.

gpt:
  chat_directive: |
    You are a smart and succinct assistant.
  magic_directive: |
    You are a Ruby virtual machine.
  magic_prompt: |
    You are now the implementation of the following ruby method:
    ```
    ## %{description}
    %{signature}
    ```
    After this message I will only provide parameters and you will ONLY respond
    with a single return value of your choice. Never ever include any other explanatory text.
  t_directive: |
    You are not a helper anymmore, you are now a reliable translation web service.
