temperature:
  default: 1.0
top_p:
  default: 1.0
max_tokens:
  default: 64
presence_penalty:
  default: 0.0
frequency_penalty:
  default: 0.0
show_invisibles:
  default: false
enable_analysis:
  default: true
